### ISSUE TITLE
"window is not defined" error when using server-side rendering

### ISSUE THREAD

**Issue by grimunit** [hellosign/hellosign-embedded#107]
When trying to load the module through webpack I'm getting a reference error that it can't find the window object:

```
/myApp/node_modules/hellosign-embedded/umd/embedded.development.js:10
})(window, function() {
   ^

ReferenceError: window is not defined
    at Object.<anonymous> (/myApp/node_modules/hellosign-embedded/umd/webpack:/HelloSign/webpack/universalModuleDefinition:10:2)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.require.extensions.(anonymous function) [as .js] (/myApp/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/myApp/node_modules/hellosign-embedded/index.js:1:
```

My versions of webpack dependencies:

```
"copy-webpack-plugin": "^4.0.0",
"html-webpack-plugin": "^3.2.0",
"webpack": "^2.2.0",
"webpack-dev-middleware": "^1.9.0",
"webpack-hot-middleware": "^2.15.0",
"webpack-isomorphic-tools": "^3.0.0",
```

**Comment by grimunit** [comment]
Hmm I'm now realizing that because I have a webpack setup that uses SSR during development and to facilitate a `dist` build that it fails when it attempts to access the `window` object while going through the SSR configuration. Looks like you guys haven't enabled the library to worth with SSR yet.

**Comment by nathanbuchar** [comment]
I'll take a look at this -- thanks for reporting.

**Comment by nathanbuchar** [comment]
Give `hellosign-embedded@next` a shot. If that works for you'll I'll release to `latest` :)

**Comment by grimunit** [comment]
Nope looks like the same thing:

```
myApp/node_modules/hellosign-embedded/umd/embedded.development.js:6281
        return window && document && document.all && !window.atob;
        ^

ReferenceError: window is not defined
    at myApp/node_modules/hellosign-embedded/umd/webpack:/HelloSign/node_modules/style-loader/lib/addStyles.js:23:1
    at myApp/node_modules/hellosign-embedded/umd/webpack:/HelloSign/node_modules/style-loader/lib/addStyles.js:12:1
    at ./node_modules/style-loader/lib/addStyles.js.module.exports (myApp/node_modules/hellosign-embedded/umd/webpack:/HelloSign/node_modules/style-loader/lib/addStyles.js:80:1)
    at Object../src/sass/embedded.scss (myApp/node_modules/hellosign-embedded/umd/webpack:/HelloSign/src/sass/embedded.scss?98d9:16:73)
    at __webpack_require__ (myApp/node_modules/hellosign-embedded/umd/webpack:/HelloSign/webpack/bootstrap:19:1)
    at Object.0 (myApp/node_modules/hellosign-embedded/umd/embedded.development.js:9393:1)
    at __webpack_require__ (myApp/node_modules/hellosign-embedded/umd/webpack:/HelloSign/webpack/bootstrap:19:1)
    at ./node_modules/common-tags/es/TemplateTag/TemplateTag.js.Object.defineProperty.value (myApp/node_modules/hellosign-embedded/umd/webpack:/HelloSign/webpack/bootstrap:83:1)
    at myApp/node_modules/hellosign-embedded/umd/embedded.development.js:97:10
    at webpackUniversalModuleDefinition (myApp/node_modules/hellosign-embedded/umd/webpack:/HelloSign/webpack/universalModuleDefinition:3:1)
```

I have webpack 2 not webpack 4 which is what is capable of utilizing the `globalObject` property of the webpack config that you added. I would love to switch to webpack 4 but could take a while based on how complicated our setup is. I think it might have to use the concept of the `target` being pointed to node or something like that. I found this that kinda talks about it: 

http://blog.jakoblind.no/ssr-webpack-bundle/

**Comment by nathanbuchar** [comment]
Appears to be a slightly different issue, but still related (using `window` within a node environment).

Unfortunately, I don't have any SSR environments to try to troubleshoot this with. Would you be able to clone this repo and try to fix it locally? If you can resolve it, please submit a PR with your solution :)

When you clone the repo, `cd` into the project folder and run [`npm link`](https://docs.npmjs.com/cli/link). This will create a global `hellosign-embedded` module that you can require in your project if you uninstall the local module. Alternatively, you can install HelloSign Embedded from a file path. If you make changes to the source code, be sure to `npm run build` or have `npm run build -- --watch` running at all times. If you makes changes to webpack you'll need to re-run the build script.

**Comment by nathanbuchar** [comment]
Actually, you might try adding this to your app's codebase somewhere:

https://github.com/reactjs/react-chartjs/issues/57#issuecomment-271106746

**Comment by grimunit** [comment]
Hmm I just tried this and it got me past that initial problem of window not being defined, but then it just failed on document not being defined. So I went down a little rabbit hole trying to see how much I would need to stub out in order to get past all the undefined browser properties and it is really starting to turn into a mess to get it all stubbed out and it's still not getting past it all.

I found the `jsdom-global` package that people have used to make testing in node get past all these browser properties, and that wasn't enough so I found someone else who suggested stubbing out even more. So I'll keep trying a little longer but so far this is how much I've added to get past undefined properties that are being used in the `hellosign-embedded` library:

```javascript
require('jsdom-global')();
const jsdom = require('jsdom');

const { JSDOM } = jsdom;
const DOM = new JSDOM('<!doctype html><html><body></body></html>');
const { window } = DOM;

window.Object = Object;
window.Math = Math;

global.window = window;
global.document = window.document;
global.navigator = {
  userAgent: 'node.js',
};

function copyProps(src, target) {
  const props = Object.getOwnPropertyNames(src)
    .filter(prop => typeof target[prop] === 'undefined')
    .map(prop => Object.getOwnPropertyDescriptor(src, prop));
  Object.defineProperties(target, props);
}
copyProps(window, global);
```

**Comment by nathanbuchar** [comment]
Hey @grimunit, just wanted to check in.

Are you up and running? If so what have you done to solve your problem? Or are you still blocked?

**Comment by grimunit** [comment]
Unfortunately I had to get prioritized on to other things. Right now I'm just using the older CDN version for my react app because that's currently working. And then for the other bundle that's just meant for processing the signature requests in the native app I'm using the newer npm imported version since that isn't server-rendered at all.

**Comment by bradpurchase** [comment]
We are having the same issue with `hellosign-embedded` where it is not working when using server-side rendering:

```
ReferenceError: window is not defined
    at Object.<anonymous> (/myApp/node_modules/hellosign-embedded/umd/webpack:/HelloSign/webpack/universalModuleDefinition:10:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/myApp/node_modules/hellosign-embedded/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

**Comment by swathikc** [comment]
If your library import looks like this 
`const Library from require('library-package');`
do
`const isBrowser = typeof window !== 'undefined';`
`const Library = isBrowser ? require('library-package'): undefined;`

If the import looks like this
`const { Library } from require('library-package');`
do
`const isBrowser = typeof window !== 'undefined';`
`const Library = isBrowser ? require('library-package').Library: undefined;`

This solved "window is not defined" problem for me. Hope this is helpful.

**Comment by nathanbuchar** [comment]
This should now be fixed in `hellosign-embedded@v2.7.2`. Thanks for your patience!

**Comment by cyrus-za** [comment]
@nathanbuchar this doesn't work for me in v2.7.2

**Comment by josiahwiebe** [comment]
I started using a dynamic import to make this work with Next.js. I also haven't tried [v2.7.2](https://github.com/hellosign/hellosign-embedded/releases/tag/v2.7.2) yet so perhaps that will allow me to eliminate some of this.

**pages/index.js**
```js
const HelloSign = dynamic(() => import('../components/HelloSign').then(mod => mod.HelloSignNoSSR), {
  loading: () => <Bar />,
  ssr: false,
})

// use <HelloSign /> component
```

**components/HelloSign.js**
```js
import Hellosign from 'hellosign-embedded'

export const HelloSignNoSSR = props => {
  const client = new HelloSign({ clientId: process.env.HS_CLIENT_ID })
  const options = {
    testMode: DEV && true,
    skipDomainVerification: DEV && true,
    container: props.container.current,
    allowCancel: true,
    ...(props.redirectUrl) && { redirectTo: props.redirectUrl },
  }
  client.open(props.signatureUrl, options)
  client.on('sign', () => {
    client.close()
    return props.onSigned()
  })
  client.on('message', data => {
    return props.onMessage(data)
  })
  return <></>
}

**Comment by jaypandya73** [comment]
And you can also load `HelloSign` client after component mounted `componentDidMount` or `useEffect` if you're using hooks this way:

```js
import('hellosign-embedded').then((module) => {
  helloSignClient = new module.default({
    clientId: clientId
  })
  helloSignClient.open(appUrl, {
    container: document.getElementById('hellosign-document-container'),
    height: 800,
    skipDomainVerification: true,
    ...
  })
})
```
so this way `hellosign-embedded` package will have access to `window` object.

**Comment by Aravin** [comment]
> Actually, you might try adding this to your app's codebase somewhere:
> 
> ```js
> if (typeof window === 'undefined') {
>   global.window = {}
> }
> ```
> 
> Via [reactjs/react-chartjs#57 (comment)](https://github.com/reactjs/react-chartjs/issues/57#issuecomment-271106746)

It worked and saved my day.

**Comment by vikasbenvanshi786** [comment]
if (typeof window === 'undefined') {
  global.window = {}
}
On Which File you Add this Code?

**Comment by Aravin** [comment]
> if (typeof window === 'undefined') {
> global.window = {}
> }
> On Which File you Add this Code?

You have to use in startup file.

Mostly `index.js` file.

**Comment by shivamragnar** [comment]
Are there any proper solutions to this? This error still persists even in 2.9 version.
