### ISSUE TITLE
Unable to use hellosign.embedded.getEditUrl in test mode

### ISSUE THREAD

**Issue by NickFoden** [hellosign/hellosign-embedded#111]
Unsure/unable to pass `test_mode: 1` to the `getEditUrl` method. 
Getting a log from API that locked templates cannot be accessed, but the template was created with test mode = 1 see bottom here. 

Is it possible to test this method before putting in production?

```javascript
 hellosign.embedded
    .getEditUrl(templateIdGoesHere)
    .then(result => etc
```

templates have been created with test_mode = 1
```javascript
const opts = {
    test_mode: 1,
   ...
  };
  hellosign.template
    .createEmbeddedDraft(opts)
```

**Comment by NickFoden** [comment]
Talking to API Team today, all templates created in test mode are locked and unable to be edited.

**Comment by nathanbuchar** [comment]
Hey @NickFoden, glad our API Support team helped you out :) Let us know if you have any other issues!
