### ISSUE TITLE
Need cross domain iframe interactions to bubble up user mouse events to prevent session timeouts.

### ISSUE THREAD

**Issue by neolytics** [hellosign/hellosign-embedded#113]
I've been digging through hellosign-embedded looking to see if I can fix an issue we are encountering.

We are in a security sensitive area and have very short login sessions based on user activity such as mouse movement etc.

Because hellosign-embedded is.. embedded and in a different domain we are unable to retrieve events from user action in the iframe and thus in cases where users have very long forms that they are creating they are getting logged out due to apparent "inactivity".

I've been digging into this all day and haven't found a workaround.  I currently don't have access to hellosign's app config (I've requested access), nor have I encountered any documentation on this particular issue.

Any advice on how to accomplish the ask?

Note:

Looker has a feature that allows for embedded domain whitelisting to allow interactions between the parent window and iframe. https://docs.looker.com/reference/embedding/embed-javascript-events

**Comment by nathanbuchar** [comment]
Just letting you know we received your report. I'm discussing internally with the team, I'll update you when I have more info :)

**Comment by Framinus** [comment]
Hi @neolytics - this is James from API Support at HelloSign. I was just discussing this with @nathanbuchar. Would you mind writing in to apisupport@hellosign.com so we can get this conversation on an internal ticket? Thank you!

**Comment by nathanbuchar** [comment]
Moving this ticket internally; closing here.
