### ISSUE TITLE
srcElement is undefined

### ISSUE THREAD

**Issue by vanwalj** [hellosign/hellosign-embedded#128]
It seems that [`srcElement`](https://github.com/hellosign/hellosign-embedded/blob/32fe889aa1c5dc19baf0a29c4003e6e723b01847/src/embedded.js#L862) is not supported by older firefox versions which is causing the script to crash

---

Update: this prevent the user from exiting the modal by clicking the upper right close button which is throwing a `TypeError: e.srcElement is undefined` when clicked

**Comment by nathanbuchar** [comment]
Thanks for the flag, we'll take a look. Sorry for the late reply, I'm the primary maintainer on the project and I've been out on vacation for the last week or so :)

**Comment by vanwalj** [comment]
No worries, I can submit a pull request fixing this issue if you want, I'll be happy to contribute!

**Comment by nathanbuchar** [comment]
That would be great, thanks @vanwalj! Be sure to take a look at the [Contributing Guidelines](https://github.com/hellosign/hellosign-embedded/blob/master/.github/CONTRIBUTING.md) :)

**Comment by scottpicquerey** [comment]
Hello, has this issue been fixed somehow ?

This error happened twice recently on the following settings :
- User 1: Windows 7 + firefox v.57
- User 2: Windows XP + firefox v.52

Maybe this setup is so old you don't want to handle it. If so, please let me know :)
Thanks for the help !

**Comment by nathanbuchar** [comment]
Sorry for the delay! This got lost on my end. This should now be fixed in `hellosign-embedded@v2.7.2`. Thanks for your patience!

**Comment by nathanbuchar** [comment]
Honestly, I don't know why I was using `evt.srcElement` here. I might have been looking something up and copied it over without thinking. Swapped it out with `evt.target`, should work now :)

**Comment by scottpicquerey** [comment]
No problem, thanks for the followup ! :)
