### ISSUE TITLE
hellosignClient.on("createTemplate") event is not actually called when template is created

### ISSUE THREAD

**Issue by ayushnawani** [hellosign/hellosign-embedded#130]
Hi
hellosignClient.on("createTemplate") event is not actually called when template is created. 

I am using this even to call my backend and when I check on my backend to get edit URL of the completed template, it throws error template not found. 

After 5-10 seconds it is actually creating the template.

Cant hellosignClient.on("createTemplate") event be triggered when the template is actually created at hellosign backend.

Thanks,

**Comment by nathanbuchar** [comment]
Noted, I'll send it over to the team :)

**Comment by latoyazamill** [comment]
Hi @ayushnawani can you please write into apisupport@hellosign.com. We will be more than happy to help investigate and resolve this issue for you. Thanks :)
