### ISSUE TITLE
HelloSign.DEFAULT_TIMEOUT = require('http').createServer().timeout;

### ISSUE THREAD

**Issue by virusmickey** [hellosign/hellosign-embedded#135]
Getting error in this line idk why im trying to implement this in react js project when i add the import statement this error comes up

![Screenshot from 2019-10-21 18-20-30](https://user-images.githubusercontent.com/6754133/67206707-d246b400-f42f-11e9-92a0-184476f775a1.png)

**Comment by latoyazamill** [comment]
Hi @virusmickey We'd love to take a deeper look at this and have a couple of ideas as to what might be taking place. Are you able to write into apisupport@hellosign.com so that we can start to investigate this in greater detail? Thanks!
