### ISSUE TITLE
Redirecting to another page in 'sign' event listener, blocked by _onBeforeUnload

### ISSUE THREAD

**Issue by ahaverty** [hellosign/hellosign-embedded#138]
I'm trying to redirect to a success page after a successful signature, but the v2 embeddable client is blocking the redirect with this onbeforeunload: https://github.com/hellosign/hellosign-embedded/blob/32fe889aa1c5dc19baf0a29c4003e6e723b01847/src/embedded.js#L917

Snippet of my relevant code:
```javascript
function startLeaseSigning(signUrl) {
    helloSignClient.open(signUrl, {
      skipDomainVerification: "<%= Figaro.env.hello_sign_skip_domain_verification.downcase %>" == "true",
      allowCancel: true
    });

    helloSignClient.on(HelloSign.events.SIGN, () => {
      window.location.replace("<%= complete_apartment_url(@apartment) %>");
    });
  }

```
It works if you click 'leave', but the confirmation popup would scare even the most technical user IMO. 
![image](https://user-images.githubusercontent.com/2920947/69551850-4d523b80-0f95-11ea-94bb-a8c30bddd48c.png)
The v1 client didn't have this issue. I also tried to get the redirectTo to work, but it throws some error within the iFrame about cross origin. I'd be open to other workarounds if that's just a bug.

Also, I had a look at the documentation on the website, and it seems to not be updated for v1: https://app.hellosign.com/api/embeddedSigningWalkthrough#EmbeddedSigningClientSide

**Comment by ahaverty** [comment]
Here's my workaround for now:
```javascript
function startLeaseSigning(signUrl) {
    var didSign = false;

    helloSignClient.open(signUrl, {
      skipDomainVerification: "<%= Figaro.env.hello_sign_skip_domain_verification.downcase %>" == "true",
      allowCancel: true
    });

    helloSignClient.on(HelloSign.events.SIGN, () => {
      didSign = true
    });

    helloSignClient.on(HelloSign.events.CLOSE, () => {
      if (didSign) {
        window.location.replace("<%= complete_apartment_url(@apartment) %>");
      }
    });
  }
```

I think it's fair to assume that onBeforeUnload shouldn't still be set by the time `HelloSign.events.SIGN` is called back. + This is now adding an unnecessary button click ("closing the iframe with 'close') to my user's journey.

**Comment by nathanbuchar** [comment]
Hey @ahaverty! Have you tried using the `redirectTo` option when calling `.open()`?

```js
client.open(signUrl, {
  // ...
  redirectTo: '<%= complete_apartment_url(@apartment) %>'
});

**Comment by nathanbuchar** [comment]
Oh I'm sorry, I missed your comment _I also tried to get the redirectTo to work, but it throws some error within the iFrame about cross origin_. That must be a bug, I'll look into that. Stay tuned!

**Comment by nathanbuchar** [comment]
Just a few days ago we actually rolled out a new signer app codebase which might be causing this issue. To help me better diagnose, can you confirm that you are still seeing the cross-origin error when using `redirectTo`?

**Comment by nathanbuchar** [comment]
@ahaverty, I just tried using the `redirectUrl` option for v1 and the `redirectTo` param for v2 and both worked without issues. Could it be that the site you're trying to redirect to is sending incompatible X-Frame-Origin headers?

**Comment by nathanbuchar** [comment]
After some internal discussion, we've come up with the following solution for you. Simply call `.close()` before replacing `window.location`. Calling this method will close the modal and also remove the `onunload` event listener.

```js
helloSignClient.on(HelloSign.events.SIGN, () => {
  // Close the HelloSign Embedded client. This will remove the
  // onunload event listener, allowing us to replace window.location
  // without the client prompting the user about unsaved changes.
  helloSignClient.close();

  window.location.replace("<%= complete_apartment_url(@apartment) %>");
 });
```

Let me know if that works :)

**Comment by davidmccoy** [comment]
i also ran into this issue and your solution worked for me @nathanbuchar! thank you!
