### ISSUE TITLE
Default modal renders beneath z-indexed elements

### ISSUE THREAD

**Issue by kybradeck** [hellosign/hellosign-embedded#140]
Hello!

Currently using the default hellosign-embedded modal in an app. Unfortunately, it's rendering beneath elements which have (quite low) z-indices.

Could you provide an option to configure a z-index for the hellosign modal, or give it a default z-index which is high? My assumption is most people would not want UI to render on top of the hellosign modal.

**Comment by nathanbuchar** [comment]
Unfortunately there's no one-size-fits-all solution for z-index. Sending it in through as an option could be possible, but it would override any other styling. If you'd like to customize the CSS, you're more than welcome! Try just applying a `z-index` property to `.x-hellosign-embedded` in your CSS. If that doesn't work, feel free to re-open.
