### ISSUE TITLE
Unkown error when signing contract

### ISSUE THREAD

**Issue by haikyuu** [hellosign/hellosign-embedded#142]
I get an unknown error when signing the contract. 

![image](https://user-images.githubusercontent.com/8558836/73950646-8fd0b680-48fc-11ea-8ac9-c000fc7668db.png)

Here is a recording of the error and how it happens: https://www.loom.com/share/85dad347b81b4edea39b1bc925b20c1a

**Comment by hazemhamedhs** [comment]
Hi Abdellah,

Thank you for bringing this case to our attention. 

Since then, we have filed a ticket to complete our conversation with you under #10258499.

Please be on the look for our response to the ticket.

**Comment by haikyuu** [comment]
Thank you Hazem
