### ISSUE TITLE
Hellosign modal covered by static navbar, can't change z-index

### ISSUE THREAD

**Issue by sadness20** [hellosign/hellosign-embedded#150]
Can't change hello sign's z-index using any of the classes like .x-hellosign-embedded, it's rendering beneath my bootstrap static navbar, it only shows up correctly when I change my navbar's z-index to 0 but then other elements go through the navbar, is there a way I can set hello sign's z-index to a higher value?

**Comment by mpryvkin** [comment]
I fixed it by assigning high enough `z-index` to `.x-hellosign-embedded` after migrating to v2.

For example:

```
// Force displaying HelloSign IFRAME over other elements
.x-hellosign-embedded {
   z-index: 2000;
}
```

**Comment by hazemhamedhs** [comment]
Thank you for offering the workaround, Michael. 
@sadness20, if you are still having any issues with the iFrame, please file a ticket by emailing us at apisupport@hellosign.com to take a look at your use-case and assist you further.
