### ISSUE TITLE
URLSearchParams issue

### ISSUE THREAD

**Issue by zaeem** [hellosign/hellosign-embedded#152]
Hi, I have migrated HelloSign API from v1 to v2 (https://github.com/hellosign/hellosign-embedded/wiki/Migration-Guide-(v1-to-v2)), it working fine locally but when I have deployed it to the server I am getting error: Cannot read property 'URLSearchParams' of undefined.

Can anyone please let me know that why this issue is occurring?

**Comment by hazemhamedhs** [comment]
Hi Zaeem,
Thank you for reaching out, and sorry for the inconvenience caused.
I've filed a ticket within our support system to get more information about your implementation.
Can you please get back to us at #10645835
I will be on the look-out for your next reply.

**Comment by zaeem** [comment]
Hi @hazemhamedhs - Can you please provide a path of #10645835 so that I can comment there.

Also, We have used like this after downloading hellosign-embedded through npm

helloSign = new HelloSign({clientId})
helloSign.open(url, {skipDomainVerification: true})
