### ISSUE TITLE
v2 does not emit error when opening signature with expired verification token

### ISSUE THREAD

**Issue by ditkin** [hellosign/hellosign-embedded#153]
Hello! 

We're upgrading from hellosign-embedded v1 to v2, and the most frequent error our customers encounter is that they clicked on an expired verification email to access our app.

In v1, when starting the embedded signing flow with an expired token, we could rely on `messageListener` catching an error event. This was very useful for us to show a custom error message to the user.

![image](https://user-images.githubusercontent.com/5571242/83798197-e57e5b00-a671-11ea-9479-a55c529ddce5.png)

However in v2, the client does not seem to emit an `message` or `error` event when starting the embedded signing flow with an expired token.

```
const client = new window.HelloSign({ clientId });

const url = `https://app.hellosign.com/editor/embeddedSign?signature_id=${signature_id}&token=${token}`;

// this message is emitted
client.on(window.HelloSign.events.SIGN, () => {
  console.log('signed')
});

client.on(window.HelloSign.events.MESSAGE, helloSignError => {
  client.close();
  // looking for a hook to show a special error message on expired token error
});

client.open(url, {
  allowCancel: true,
  debug: true,
});
```

Any advice about how to capture this error is greatly appreciated!

**Comment by hazemhamedhs** [comment]
Thank you for reaching out, and sorry for the inconvenience caused. 

This specific error has not been built so far in the V2 embedded library. That said, I can file a feature request on your behalf with the engineering team.

In the meantime, we highly recommend you to listen to your callback event "sign_url_invalid" when a signer is hitting an expired link to regenerate a new sign_url link. You can read more about this event in the "Event names" table linked below
https://app.hellosign.com/api/reference#Objects 

If you would like to inquire about the status of this, please email us at apisupport@hellosign.com.

Feel free to reach out to us if you have any further questions.

**Comment by ditkin** [comment]
@hazemhamedhs if possible, if you could file a feature request for this, that'd be great. It helps our customers understand why they can't sign in the most common case.

Just looking to confirm this is how we'd solve this with callbacks:
1) Our backend would set up an endpoint to be hit on `sign_url_invalid`
2) Our backend would expose an endpoint that verifies whether a url or token is valid for signing
3) Before launching the embedded esignature flow, our frontend would hit the new backend endpoint and verify whether the url or token that's about to be used is valid for signing

Is this correct? Thanks in advance!

**Comment by hazemhamedhs** [comment]
@ditkin Totally possible, David.

I went ahead and filed a feature request on your behalf [internal reference - HSAPI-I-491]. It typically takes about 2-4 weeks for us to reach a decision on a product feature request. You can reach out to us at anytime to check on the status of the request.

Your flow sounds about right. Here is more information about our callback events and how to set them up [[LINK](https://app.hellosign.com/api/eventsAndCallbacksWalkthrough)]. Also, please keep in mind that Sign_urls and edit_urls have a TTL (Time to live) of one hour. [[LINK](https://faq.hellosign.com/hc/en-us/articles/115001991408-How-long-sign-urls-and-edit-urls-last)]

If any questions or new support needs come up, please do not hesitate to contact us at apisupport@hellosign.com.
