### ISSUE TITLE
Receive a createTemplate event even when the user cancels using the toolbar

### ISSUE THREAD

**Issue by epricer** [hellosign/hellosign-embedded#154]
Using version 2.7.2, Embedded Template Creation
If the user clicks the Close "X" on the left side of the toolbar:
![image](https://user-images.githubusercontent.com/9825333/83825885-8daf1680-a6a8-11ea-8384-7a5106782aea.png)
The client fires a series of events INCLUDING a createTemplate Event, but NOT a cancel event. This happens whether or not 'allow cancel' is enabled, and whether or not the template has all of the required elements provided. No accompanying webhook is called, so apparently the template is not created. 
I would expect that a cancel event would be fired, and more importantly, that a 'createTemplate' event would NOT be fired.

**Comment by jbkly** [comment]
I think this has been resolved, can the devs confirm?

**Comment by johnnycupcakes** [comment]
Hello, thank you both for your comments.

You are correct @jbkly. The the Close "X" on the left side of the toolbar has been removed. I'll close this issue out - thanks again!
