### ISSUE TITLE
Getting error - "Could not save! DOMException: Blocked a frame with origin "https://app.hellosign.com" from accessing a cross-origin frame..."

### ISSUE THREAD

**Issue by BarrBozzO** [hellosign/hellosign-embedded#158]
Hey Hellosign Team

Can't save template changes from embedded window. I am using a **free plan** account and testing in `localhost`

Getting next error:

```
Could not save! DOMException: Blocked a frame with origin "https://app.hellosign.com" from accessing a cross-origin frame. at https://cdn.hellosign.com/1.90.4/build
```

----

### Steps:

1. Create a new draft template with: 

```
const opts = {
  test_mode: 1,
  clientId: "MY-CLIENT_ID",
  ...
};

hellosign.template
  .createEmbeddedDraft(opts)
```

2. using `edit_url` from prev step, open embedded window on Frontend side with:

```
const hellosign = new HelloSign({
      clientId: 'CLIENT-APP-ID',
      debug: true,
      testMode: true,
      skipDomainVerification: true
    });

hellosign.open(edit_url, {
          debug: true,
          testMode: true,
          skipDomainVerification: true
        });
```

3. Add fields and click **"Continue"**.

4. Get error mentioned above

**Comment by hazemhamedhs** [comment]
Hi Konstantin,

Thank you for reaching out, and sorry for the inconvenience caused. 

I've replied to your ask with us under ticket number #10956668 to tackle the root cause of the error accordingly.

I will be on the look-out for your next reply on the ticket.
