### ISSUE TITLE
Clarify event behavior change in v1 to v2 Migration Guide

### ISSUE THREAD

**Issue by janetanne** [hellosign/hellosign-embedded#160]
Customer wrote in to tell us that the migration from v1 to v2 had a major change in how events are handled, and that this behavior change is not explained in the migration guide:

>Previously, the messageListener existed inside of the open method, now the event listeners exist on the global instance, and remain on the global instance until the browser is manually refreshed.

>Event listener management was not something we had to think about in v1 of the SDK, so we were not expecting that by following the migration guide and it’s recommended syntax changes that we would suddenly be responsible for managing our sign events, sniffing out the signatureRequestId and ensuring we aren’t firing off duplicate requests to our API.

Request to add a section about the changes in event behavior (tied to the on() and off() methods) to the migration guide.

Related ticket number: 11001942
Internal reference: 10214

**Comment by nathanbuchar** [comment]
Fixed in https://github.com/hellosign/hellosign-embedded/wiki/Migration-Guide-(v1-to-v2)
