### ISSUE TITLE
Request: Add an event when documents ready

### ISSUE THREAD

**Issue by Sergio-Amount** [hellosign/hellosign-embedded#162]
The current `ready` event fires before the loading animation is complete.
It would be useful for our company to have an event that fires when the loading animation is complete and the documents are visible.

<img width="597" alt="Screen Shot 2020-08-26 at 4 46 45 PM" src="https://user-images.githubusercontent.com/61711579/91367615-ce0bc580-e7bb-11ea-97ef-1e9275f8cbd6.png">

**Comment by hazemhamedhs** [comment]
Hi Sergio,

Thank you for reaching out.

I've let my product team know about your request to add `doucment_visible` event, and I'll let you know about that idea as we think it through. Once it has been passed to the developing stage and released, you will make sure to keep you posted.

In the meantime, please feel free to email us at apisupport@hellosign.com if any further help needed.

_Internal report- DEV-10563_
