### ISSUE TITLE
Add Ability to Add Signer Attachments to Draft Signature Request

### ISSUE THREAD

**Issue by noseworthy** [hellosign/hellosign-embedded#171]
We're able to add signer attachments via the API when creating an embedded unclaimed draft signature request, but in our app, we don't know what signers or attachments will be included in the signature request until the draft is opened in the embedded signature request editor and edited by the user.

Is is possible to add the ability to specify signer attachments in the embedded draft signature request editor so that our users can add attachments for their signers?

Thanks!

**Comment by nathanbuchar** [comment]
Hi @noseworthy, sorry for the late reply. The HelloSign Embedded library only wraps around our webapp, but it sounds like you have a question about the API. If you haven't already, I'd recommend reaching out to apisupport@hellosign.com
