### ISSUE TITLE
Issue with Webpack loaders

### ISSUE THREAD

**Issue by bluespore** [hellosign/hellosign-embedded#27]
## Description

I can't seem to use the library in my react / webpack setup as it seems to have an issue with the way `package.json` is referencing the `version` key [here](https://github.com/HelloFax/hellosign-embedded/blob/master/src/embedded.js#L252).

As far as I understand I've already got json loaders in my config, but surely that should have no bearing on using the library? Is there a compiled source that the package `main` can reference instead?

## Usage

```js
import HelloSign from 'hellosign-embedded';
window.HelloSign = HelloSign;
```

## Version number

1.2.5

## CLI Error

```
ERROR in ./~/hellosign-embedded/package.json
Module parse failed: /Users/sean/Ento/app/ento/onboarding/app-candidate/node_modules/hellosign-embedded/package.json Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
| {
|   "name": "hellosign-embedded",
|   "version": "1.2.5",
|   "description": "A JavaScript library required for embedding HelloSign features into your webapp. For more information, see our API documentation at https://www.hellosign.com/api/documentation.",
 @ ./~/hellosign-embedded/src/embedded.js 252:17-43
```

**Comment by thienanle** [comment]
In case anyone else was having this issue, doing this solved it for me:

In webpack DLL plugin settings, add `hellosign-embedded` to excludes:

"dllPlugin": {
  "exclude": [
    "hellosign-embedded"
  ]
}
