### ISSUE TITLE
Uncaught Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by thienanle** [hellosign/hellosign-embedded#31]
I'm getting the error below. My project uses babel-polyfill. Any ideas?

![image](https://cloud.githubusercontent.com/assets/874402/25168934/957da2b4-2528-11e7-8d5d-a6e63f52ed69.png)

**Comment by johncmunson** [comment]
Also getting this error. My project uses gulp/babel, but vendor code such as HelloSign does not get transpiled. Which makes me think this may be a bug in the `hellosign-embedded` package

**Comment by aprudnikoff** [comment]
I have the same issue. My project uses webpack/babel.
