### ISSUE TITLE
Importing via webpack exports as an immutable object

### ISSUE THREAD

**Issue by jyoung488** [hellosign/hellosign-embedded#47]
When importing the hellosign-embedded module via webpack, it's exported as an immutable object so this.clientId = appClientId fails since there's no supported setter. Perhaps another way is needed to store the appClientId to address this.

**Comment by nathanbuchar** [comment]
@jyoung488 Can you provide a code example with your Webpack config? I've also recently updated the [demo](https://github.com/HelloFax/hellosign-embedded/blob/master/demo/src/index.js) to use the HelloSign npm module as opposed to the CDN source
