### ISSUE TITLE
Cancel Button Missing is missing V2

### ISSUE THREAD

**Issue by KhalilMohammad** [hellosign/hellosign-embedded#87]
My existing project was updated automatically to 1.6.x .
I reported this issue in #40 . That issue was resolved by changing ux version.
I updated version of hellosign embedded to latest 2.0 but cancel button is still missing.
Below is the config for hellosign-embedded
client.open(data.signUrl, {
                    debug: IsDevelopment,
                    skipDomainVerification: IsDevelopment,
                    allowCancel: true
                });

I want to display modal close button.

**Comment by nathanbuchar** [comment]
Hi @KhalilMohammad,

Just to confirm, which workflow are you using HelloSign Embedded with? Signing, requesting, or templates?

**Comment by KhalilMohammad** [comment]
I am using Signing flow with template.
To provide some context. I am using npm for package management.
Previous I was using ^1.5.2 which means latest minor version.
I then tried V2 but same problem.
I have now fixed to version 1.5.2 which is working. I will provide you with screen shots later.

**Comment by nathanbuchar** [comment]
Thanks. So you're expecting there to be a close button in the top right of the modal window? Or is the "Close" menu item missing when you press the "…" in the top left of the modal? Both? Screenshots would help if you can provide, thanks :-)

**Comment by KhalilMohammad** [comment]
Cross at the top left disappear v2.0 and v1.5.x (probably 1.5.9 or which ever is latest)
I repeat again,I use npm and webpack4.0.
I do not if that has an effect on missing cancel button.

![image](https://user-images.githubusercontent.com/17926533/46982753-04278b00-d0f7-11e8-9fd5-45c929efbb57.png)

**Comment by nathanbuchar** [comment]
So after some digging, it looks like close button was intentionally removed in UX v2 of HelloSign Embedded v1, and this change followed through into v2.

I'm going to follow up with a few team members about why this change was made and whether or not it should be added back in. In the meantime, users can close the modal by clicking on the ⋮ menu in the top left (after clicking "Get Started"), and selecting "Close". I'll update you when I have more information :)

**Comment by nathanbuchar** [comment]
I should also add, if you're using HelloSign Embedded v1, be sure to add the `uxVersion: 2` parameter in your `HelloSign.open()` call. This will add the "⋮" in the top left of the window, to the right of the HelloSign logo.

**Comment by KhalilMohammad** [comment]
In my opinion, this is bad ui/ux. Not everybody knows what "⋮" means

**Comment by KhalilMohammad** [comment]
Also feel free to close this issue.I have fixed my hellosign version to 1.5.2 with uxVersion:1

**Comment by nathanbuchar** [comment]
Thanks for your feedback @KhalilMohammad!

I agree, users expect certain affordances for common UI elements (like modals). I'll bring this up at the next HelloSign Embedded meeting :-)
