### ISSUE TITLE
Failed to minify the code from this file - v2.1.1

### ISSUE THREAD

**Issue by binhxn** [hellosign/hellosign-embedded#93]
## Description
My code is built using `create-react-app` and I'm using `hellosign-embedded: ^2.1.1`
When I run `npm run build` I get this error:

```
Failed to minify the code from this file: 

 	./node_modules/hellosign-embedded/umd/embedded.production.min.js:1:3984

Read more here: http://bit.ly/2tRViJ9
```

I tried following the direction in the link provided through the docs and updating the necessary files, but I'm getting no result; same errors. Do you have any suggestions to fix this?

**Comment by nathanbuchar** [comment]
I'll take a look at this in a bit :) thanks for noting it

**Comment by nathanbuchar** [comment]
Update to 2.1.2 and give it another shot :)
