### ISSUE TITLE
v2.1.0 & v2.1.0: Standard build behaviour includes both dev and prod.min versions in bundle

### ISSUE THREAD

**Issue by ryan-kimber** [hellosign/hellosign-embedded#95]
Maybe I am misusing this library, but it seems like if I do the following: 

`import hellosign from 'hellosign-embedded`

... then my browserify'd or webpack'd application is going to be built with both the development and production .js files compiled into it, bloating the size of my application instead of making it smaller.

Is there some other way we should be including the library in our build to avoid this double-inclusion?

**Comment by nathanbuchar** [comment]
Hmm, that's certainly not the intended behavior. I'll take a look at this and see if I can reproduce. Thanks for flagging!

**Comment by nathanbuchar** [comment]
Should be good now if you update to v2.1.2 :)
