### ISSUE TITLE
embedded.production.min.js includes arrow functions that will not run in older browsers

### ISSUE THREAD

**Issue by ryan-kimber** [hellosign/hellosign-embedded#99]
Thanks for the extremely quick turnaround on issue #95.

We are having to babelify the code ourselves to get rid of the arrow functions, even on the latest 2.1.2 version. I haven't looked back as far as 2.0, but this seems to affect 2.1.0 and 2.1.1 as well.

**Comment by AHelpfulFriend** [comment]
We are also having this problem. At a minimum, the dependency on debug is using the untranspiled files from src instead of the transpiled (IE-safe) files from dist. I haven't dug in far enough to see if any other dependency code is causing trouble.

**Comment by nathanbuchar** [comment]
Oh no! Thanks for flagging. This is certainly not intended. I'll dig into this ASAP.

I do have Babel in place to transpile ES6 syntax, but looks like I'm ignoring `node_modules`. Are ya'll using the npm version of HelloSign Embedded? Or the CDN version?

**Comment by AHelpfulFriend** [comment]
We're using the npm version.

**Comment by nathanbuchar** [comment]
Should be 💯 now :) Slightly bigger lib size, but not by much.
